### ISSUE TITLE
UserStories Priorisieren

### ISSUE THREAD

**Issue by codingfabi** [Locke21/srquiz#3]
Die UserStories müssen priorisiert werden. Das machen wir anhand ihrer Reihenfolge in der "Pending - Tabelle". Ich habe einen ersten Entwurf vorgenommen, wie ichs mir gedacht hätte. Am besten schaut ihr nochmal drüber und ändert das ab, was ihr anders seht. Besonders, ob der Einzel- oder der Mehrspielermodus zu priorisieren ist sollten wir nochmal diskutieren.

**Comment by Locke21** [comment]
Ja also für mich passt das so! Gute Arbeit @codingfabi ! 👍 
#doSomeEpicShit
