### ISSUE TITLE
Als User möchte ich mich einloggen, um auf mein Benutzerprofil zugreifen zu können.

### ISSUE THREAD

**Issue by codingfabi** [Locke21/srquiz#7]

**Comment by Locke21** [comment]
Aktuell ist das UI des Login-Screens fertig und jetzt muss die Logik eingebaut werden! 

<img width="356" alt="bildschirmfoto 2017-06-12 um 23 33 51" src="https://user-images.githubusercontent.com/11315321/27056298-cdf7a6b6-4fc7-11e7-8cba-aeedbc27a7bb.png">
<img width="354" alt="bildschirmfoto 2017-06-12 um 23 34 09" src="https://user-images.githubusercontent.com/11315321/27056297-cdf2b9da-4fc7-11e7-9d17-593049382d9a.png">

**Comment by Locke21** [comment]
Done!
